# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "ahci"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d4687736-d427-4c82-aead-cc8d876c8cf9";
    fsType = "btrfs";
    options = [ "subvol=@,ssd" ];
  };

  fileSystems."/etc" = {
    device = "/dev/disk/by-uuid/d4687736-d427-4c82-aead-cc8d876c8cf9";
    fsType = "btrfs";
    options = [ "subvol=@etc,ssd,noatime" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/d4687736-d427-4c82-aead-cc8d876c8cf9";
    fsType = "btrfs";
    options = [ "subvol=@nix,ssd,noatime" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/d4687736-d427-4c82-aead-cc8d876c8cf9";
    fsType = "btrfs";
    options = [ "subvol=@logs,ssd,noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FF21-2B5C";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
